[project]
name = "mojo-gobi"
version = "0.1.0"
description = "A Mojo CLI app similar to uv, stricter for AI projects"
dependencies = [
    "rich",
    "cx-Freeze",
    "tomli-w",
]

[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"
